<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Radio.Application\Radio.Application.csproj" />
    <ProjectReference Include="..\Radio.Infrastructure\Radio.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
